name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build Github-Pages
        run: |
          asv --config=.github/asv.conf.json publish --no-pull
      - name: Build PR index page
        run: |
          python .github/create_pr_pages.py

      - name: Show file tree
        run: tree html

      - name: Upload bundled page
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: html

  deploy-page:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Deploy gh-pages
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download bundled page
        uses: actions/download-artifact@v2
        with:
          name: html
          path: html

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
