name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install ASV
        run: |
          pip install asv virtualenv

      - name: Build Github-Pages
        run: |
          asv --config=.github/asv.conf.json publish --no-pull

      - name: Upload bundled page
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: html

  deploy-page:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download bundled page
        uses: actions/download-artifact@v2
        with:
          name: html
          path: html

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
